import {IAttribute} from './lib/attribute';
import {IAuthor} from './lib/author';
import {ICharacter} from './lib/character';
import {IEffect} from './lib/effect';
import {IFocus} from './lib/focus';
import {IInjury} from './lib/injury';
import {IItem} from './lib/item';
import {IMarkdownString} from './lib/markdown-string';
import {IModule} from './lib/module';
import {IReference} from './lib/reference';
import {IRule} from './lib/rule';
import {ISpecies} from './lib/species';
import {ISpell} from './lib/spell';

export type Attribute = IAttribute;
export type Author = IAuthor;
export type Character = ICharacter;
export type Effect = IEffect;
export type Focus = IFocus;
export type Injury = IInjury;
export type Item = IItem;
export type MarkdownString = IMarkdownString;
export type Module = IModule;
export type Reference = IReference;
export type Rule = IRule;
export type Species = ISpecies;
export type Spell = ISpell;
