name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@powerd6'

    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

    - run: npm run build --if-present
  
    - uses: actions/cache@v3
      id: build-cache
      with:
        path: ./* # Cache the whole project
        key: 'build-${{ matrix.node-version }}-${{ github.sha }}'

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x]

    needs: [build]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@powerd6'
  
    - uses: actions/cache@v3
      id: build-cache
      with:
        path: ./* # Cache the whole project
        key: 'build-${{ matrix.node-version }}-${{ github.sha }}'
    
    - run: npm test
